<!DOCTYPE html>
<html lang="en"><head>
<script src="https://multiplex.up.railway.app/socket.io/socket.io.js"></script>
<script src="https://multiplex.up.railway.app/client.js"></script>
<script src="reg-cat-part1_files/libs/clipboard/clipboard.min.js"></script>
<script src="reg-cat-part1_files/libs/quarto-html/tabby.min.js"></script>
<script src="reg-cat-part1_files/libs/quarto-html/popper.min.js"></script>
<script src="reg-cat-part1_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="reg-cat-part1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="reg-cat-part1_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="reg-cat-part1_files/libs/quarto-html/quarto-syntax-highlighting-dark-707d8167ce6003fca903bfe2be84ab7f.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <title>reg-cat-part1</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="reg-cat-part1_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="reg-cat-part1_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #f8f8f2;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #f8f8f2; } /* Normal */
    code span.al { color: #f07178; } /* Alert */
    code span.an { color: #d4d0ab; } /* Annotation */
    code span.at { color: #00e0e0; } /* Attribute */
    code span.bn { color: #d4d0ab; } /* BaseN */
    code span.bu { color: #abe338; } /* BuiltIn */
    code span.cf { color: #ffa07a; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #abe338; } /* Char */
    code span.cn { color: #ffd700; } /* Constant */
    code span.co { color: #f8f8f2; font-style: italic; } /* Comment */
    code span.cv { color: #ffd700; } /* CommentVar */
    code span.do { color: #f8f8f2; } /* Documentation */
    code span.dt { color: #ffa07a; } /* DataType */
    code span.dv { color: #d4d0ab; } /* DecVal */
    code span.er { color: #f07178; text-decoration: underline; } /* Error */
    code span.ex { color: #00e0e0; font-weight: bold; } /* Extension */
    code span.fl { color: #d4d0ab; } /* Float */
    code span.fu { color: #ffa07a; } /* Function */
    code span.im { color: #abe338; } /* Import */
    code span.in { color: #d4d0ab; } /* Information */
    code span.kw { color: #ffa07a; font-weight: bold; } /* Keyword */
    code span.op { color: #ffa07a; } /* Operator */
    code span.ot { color: #00e0e0; } /* Other */
    code span.pp { color: #dcc6e0; } /* Preprocessor */
    code span.re { color: #00e0e0; background-color: #f8f8f2; } /* RegionMarker */
    code span.sc { color: #abe338; } /* SpecialChar */
    code span.ss { color: #abe338; } /* SpecialString */
    code span.st { color: #abe338; } /* String */
    code span.va { color: #00e0e0; } /* Variable */
    code span.vs { color: #abe338; } /* VerbatimString */
    code span.wa { color: #dcc6e0; } /* Warning */
  </style>
  <link rel="stylesheet" href="reg-cat-part1_files/libs/revealjs/dist/theme/quarto-b37f5d03d02dc7343a457c3c4be4584f.css">
  <link href="reg-cat-part1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="reg-cat-part1_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="reg-cat-part1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="reg-cat-part1_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-dark">
  <div class="reveal">
    <div class="slides">


<section id="reminder-keep-up-with-textbook-readings" class="slide level2 section-header" data-background="linear-gradient(135deg, #b71c1c 0%, #c62828 50%, #d32f2f 100%)">
<h2>Reminder: Keep up with Textbook Readings</h2>
</section>
<section id="linear-models-with-categorical-predictors" class="slide level2 section-header" data-background="linear-gradient(135deg, #0277bd 0%, #0288d1 50%, #039be5 100%)">
<h2>Linear Models with Categorical Predictors</h2>
</section>
<section id="section" class="slide level2" data-background-image="images/ai-image-4.png" data-background-size="cover">
<h2></h2>
<div class="overlay-text-bottom">
<p><strong>Scenario:</strong> Does the new onboarding program actually work?</p>
</div>
</section>
<section id="todays-question" class="slide level2 content-light">
<h2>Today’s Question</h2>
<blockquote>
<p>“A company wants to know if their new onboarding program improves performance. The new-program group has higher ratings. The CEO is ready to roll out the program company-wide. Should they?”</p>
</blockquote>
<blockquote>
<p>“Not so fast—the new-program employees also have more education. Is the program effective, or are we just seeing an education effect?”</p>
</blockquote>
<p>We’ll revisit this question—much later. By the end of this topic, you’ll be able to answer this question properly.</p>
</section>
<section id="learning-objectives" class="slide level2">
<h2>Learning Objectives</h2>
<p>By the end of this lecture, you will be able to:</p>
<ol type="1">
<li>Explain that ŷ represents an estimate of the mean y for people with a given set of predictor values</li>
<li>Explain why categorical variables require special coding in regression</li>
<li>Interpret regression output when using treatment (dummy) coding</li>
<li>Calculate predicted scores by “thinking horizontally” across the predictor matrix</li>
<li>Interpret coefficients using the “holding constant” framework</li>
<li>Explain why regression coefficients change when predictors are added</li>
<li>Report regression results using APA 7 formatting conventions</li>
</ol>
</section>
<section id="todays-goalsin-simple-terms" class="slide level2">
<h2>Today’s Goals—In Simple Terms</h2>
<table class="caption-top">
<colgroup>
<col style="width: 53%">
<col style="width: 46%">
</colgroup>
<thead>
<tr class="header">
<th>By the end of today…</th>
<th>In simpler terms…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Understand what ŷ means</td>
<td>Predicting the <strong>average</strong> for people like them</td>
</tr>
<tr class="even">
<td>Use treatment coding</td>
<td>Turn categories into <strong>0s and 1s</strong> that regression can use</td>
</tr>
<tr class="odd">
<td>“Think horizontally”</td>
<td>Plug values into an equation and <strong>calculate predictions</strong></td>
</tr>
<tr class="even">
<td>Understand “holding constant”</td>
<td>Compare groups <strong>fairly</strong> by accounting for other differences</td>
</tr>
<tr class="odd">
<td>Understand confounding</td>
<td>See how results can <strong>change dramatically</strong> when we account for other variables</td>
</tr>
</tbody>
</table>
</section>
<section id="key-r-functions-well-use" class="slide level2">
<h2>Key R Functions We’ll Use</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 42%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>What it does</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>as.factor()</code></td>
<td>Converts text to a categorical variable</td>
<td><code>as.factor(department)</code></td>
</tr>
<tr class="even">
<td><code>fct_relevel()</code></td>
<td>Sets which group is the reference (comparison) group</td>
<td><code>fct_relevel(location, "office")</code></td>
</tr>
<tr class="odd">
<td><code>lm()</code></td>
<td>Runs the linear regression model</td>
<td><code>lm(y ~ x, data = df)</code></td>
</tr>
<tr class="even">
<td><code>tidy()</code></td>
<td>Extracts coefficients into a clean table</td>
<td><code>tidy(model)</code></td>
</tr>
<tr class="odd">
<td><code>glance()</code></td>
<td>Extracts model-level statistics (R², F, etc.)</td>
<td><code>glance(model)</code></td>
</tr>
<tr class="even">
<td><code>augment()</code></td>
<td>Adds predictions and residuals to your data</td>
<td><code>augment(model, data = df)</code></td>
</tr>
<tr class="odd">
<td><code>cohen.d()</code></td>
<td>Calculates Cohen’s d effect size</td>
<td><code>cohen.d(y ~ group, data = df)</code></td>
</tr>
</tbody>
</table>
</section>
<section id="part-1-conceptual-foundation" class="slide level2 section-header" data-background="linear-gradient(135deg, #b71c1c 0%, #c62828 50%, #d32f2f 100%)">
<h2>Part 1: Conceptual Foundation</h2>
</section>
<section id="what-does-ŷ-actually-mean" class="slide level2 content-light">
<h2>What Does ŷ Actually Mean?</h2>
<p><strong>Recall notation:</strong> ŷ is our predicted value. The hat means “estimated” or “predicted.”</p>
<p>When we calculate ŷ for a person, we are NOT predicting that specific person’s score.</p>
<p>We are estimating the <strong>mean y for all people with those predictor values</strong>.</p>
</section>
<section id="an-analogy-nba-height" class="slide level2 content-light">
<h2>An Analogy: NBA Height</h2>
<p>Imagine someone tells you: “The average height of NBA players is 6’6”.”</p>
<p>Now you meet an NBA player named Marcus. What’s your best guess for his height?</p>
<ul>
<li><strong>Your guess:</strong> 6’6” (the average)</li>
<li><strong>Reality:</strong> Marcus might be 6’2” or 7’1”—individuals vary!</li>
</ul>
<p><strong>Key insight:</strong> Your guess of 6’6” is NOT a claim that Marcus is exactly 6’6”. It’s your best guess <em>because you know nothing else about him</em> except that he’s an NBA player.</p>
<p>ŷ works the same way: it’s our best guess for someone based on their predictor values, knowing that individuals will vary around that average.</p>
</section>
<section id="population-vs.-individual" class="slide level2 content-light">
<h2>Population vs.&nbsp;Individual</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/population-vs-individual-1.png" class="quarto-figure quarto-figure-center" width="864"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="the-regression-line-connects-means" class="slide level2 content-light">
<h2>The Regression Line Connects Means</h2>
<ul>
<li>At each x value, there’s a whole distribution of y values</li>
<li>The regression line passes through the <strong>mean</strong> of each distribution</li>
<li>This is why we call it “conditional mean”—the mean of y, conditional on x</li>
</ul>
<p><strong>Plain English:</strong> “Conditional mean” just means “the average for a specific subgroup.” For example, the mean salary <em>given that</em> someone has 5 years of experience. The word “conditional” = “given that” or “for people who have.”</p>
</section>
<section id="visualizing-the-conditional-distributions" class="slide level2">
<h2>Visualizing the Conditional Distributions</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/demo-graph-1.png" class="quarto-figure quarto-figure-center" style="width:85.0%"></p>
</figure>
</div>
<p>At each experience level, there’s a <strong>distribution</strong> of performance values. The regression line connects the <strong>means</strong> of these distributions.</p>
</section>
<section id="visualizing-what-ŷ-means" class="slide level2">
<h2>Visualizing What ŷ Means</h2>
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/demo-graph-2.png" class="quarto-figure quarto-figure-center" style="width:85.0%"></p>
</figure>
</div>
<p>The point on the regression line is our <strong>estimate of the mean</strong> for the subpopulation at that x value.</p>
</section>
<section id="what-ŷ-means-a-concrete-example" class="slide level2 content-light">
<h2>What ŷ Means: A Concrete Example</h2>
<p><strong>Example:</strong> Suppose Bob has 5 years of experience and we predict his performance as 75.</p>
<ul>
<li>This 75 is NOT a prediction specific to Bob</li>
<li>It’s our estimate of the average performance for ALL employees with 5 years of experience</li>
</ul>
<p><strong>Think of it this way:</strong> If we could find thousands of people with exactly 5 years of experience, their average performance would be about 75. Bob is just one person from that population—his actual score could be higher or lower.</p>
</section>
<section id="what-ŷ-means-vs.-what-it-doesnt-mean" class="slide level2 content-light">
<h2>What ŷ Means vs.&nbsp;What It Doesn’t Mean</h2>
<table class="caption-top">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>What ŷ = 75 means</th>
<th>What ŷ = 75 does NOT mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Average performance for all 5-year employees</td>
<td>Bob will score exactly 75</td>
</tr>
<tr class="even">
<td>Our best single guess for anyone with 5 years</td>
<td>A guarantee about Bob’s score</td>
</tr>
<tr class="odd">
<td>The center of the distribution at x = 5</td>
<td>That there’s no variation in y at x = 5</td>
</tr>
</tbody>
</table>
</section>
<section id="connection-to-categorical-predictors" class="slide level2 content-light">
<h2>Connection to Categorical Predictors</h2>
<ul>
<li>With a continuous predictor:
<ul>
<li>ŷ estimates the mean for people at that x value</li>
</ul></li>
<li>With a categorical predictor:
<ul>
<li>ŷ estimates the mean for people in that group</li>
</ul></li>
</ul>
<blockquote>
<p><strong>The predicted value for everyone in a group will be the group mean!</strong></p>
</blockquote>
<p>Keep this in mind—we’ll see it in action shortly.</p>
</section>
<section id="notation-dictionary" class="slide level2 smaller">
<h2>Notation Dictionary</h2>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 46%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Plain English</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ŷ</td>
<td>“y-hat” = our prediction</td>
<td>ŷ = 72 means “we predict 72”</td>
</tr>
<tr class="even">
<td>b₀</td>
<td>The starting point (intercept)</td>
<td>b₀ = 72 means “we start at 72”</td>
</tr>
<tr class="odd">
<td>b₁</td>
<td>How much to add/subtract for a predictor</td>
<td>b₁ = 8 means “add 8 for this group”</td>
</tr>
<tr class="even">
<td>× 1</td>
<td>“Yes, include this”</td>
<td>8 × 1 = 8 (the 8 is included)</td>
</tr>
<tr class="odd">
<td>× 0</td>
<td>“No, skip this”</td>
<td>8 × 0 = 0 (the 8 disappears)</td>
</tr>
<tr class="even">
<td>Int</td>
<td>The intercept column (always 1s)</td>
<td>Everyone gets 1 here</td>
</tr>
<tr class="odd">
<td>c1, c2, c3</td>
<td>Contrast columns (0s and 1s)</td>
<td>Identify which group someone belongs to</td>
</tr>
</tbody>
</table>
</section>
<section id="recall-the-intercept-is-just-another-weight" class="slide level2 content-minimal">
<h2>Recall: The Intercept is Just Another Weight</h2>
<p>The intercept is just another regression weight—applied to a column of ones.</p>
<p>Before we add categorical predictors, let’s make sure we understand how the intercept works.</p>
</section>
<section id="section-1" class="slide level2" data-background-image="images/ai-image-1.png" data-background-size="cover">
<h2></h2>
<div class="overlay-text-bottom">
<p><strong>Scenario:</strong> How engaged are employees at this company?</p>
</div>
</section>
<section id="employee-engagement-data" class="slide level2">
<h2>Employee Engagement Data</h2>
<p>We surveyed employees and asked them to rate their engagement on a scale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href=""></a>engage_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/engagement_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: right;">engagement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Oscar</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pam</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Quentin</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rosa</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sam</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tara</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uma</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">74</td>
</tr>
<tr class="even">
<td style="text-align: left;">Victor</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">71</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wendy</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xavier</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">72</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Our question:</strong> What’s our prediction for any employee’s engagement?</p>
</section>
<section id="the-intercept-only-model-mean" class="slide level2">
<h2>The Intercept-Only Model: Mean</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>lm_intercept <span class="ot">&lt;-</span> <span class="fu">lm</span>(engagement <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> engage_data)</span>
<span id="cb2-2"><a href=""></a><span class="fu">tidy</span>(lm_intercept)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0.8164966</td>
<td style="text-align: right;">88.18163</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The intercept is 72. What is 72?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href=""></a><span class="fu">mean</span>(engage_data<span class="sc">$</span>engagement)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 72</code></pre>
</div>
</div>
<p>It’s the mean!</p>
</section>
<section id="the-intercept-only-model-sd-and-mse" class="slide level2">
<h2>The Intercept-Only Model: SD and MSE</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href=""></a>lm_intercept <span class="ot">&lt;-</span> <span class="fu">lm</span>(engagement <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> engage_data)</span>
<span id="cb5-2"><a href=""></a><span class="fu">glance</span>(lm_intercept)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2.581989</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">NA</td>
<td style="text-align: right;">-23.14818</td>
<td style="text-align: right;">50.29637</td>
<td style="text-align: right;">50.90154</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Sigma is 2.58 - the SD of the residuals.</p>
<h3 id="this-is-the-same-as-sd-scores">This is the same as SD scores</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href=""></a><span class="fu">sd</span>(engage_data<span class="sc">$</span>engagement)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.581989</code></pre>
</div>
</div>
<p>The SD of engagement scores is 2.58</p>
<h3 id="recall-psyc-6060">Recall PSYC 6060</h3>
<p><span class="math inline">\(MSE = SD(residuals)^2 = \text{sigma}^2 =(2.581989)^2 = 6.666667\)</span></p>
<h3 id="we-get-mse-from-the-glance-output">We get MSE from the glance() output!</h3>
</section>
<section id="augment-the-data" class="slide level2">
<h2>Augment the Data</h2>
<p>Make predicted scores for each person</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href=""></a>engage_augmented <span class="ot">&lt;-</span> <span class="fu">augment</span>(lm_intercept, <span class="at">data =</span> engage_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>What does <code>augment()</code> do?</strong> It takes our model and adds predictions (<code>.fitted</code>) and residuals (<code>.resid</code>) back to our original data. It’s like asking R: “For each person, what did you predict?”</p>
<div class="cell augment">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: right;">engagement</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.resid</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Oscar</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.738613</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pam</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-4</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.297341</td>
<td style="text-align: right;">0.2962963</td>
<td style="text-align: right;">-1.6329932</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Quentin</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.500000</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">1.2247449</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rosa</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.635231</td>
<td style="text-align: right;">0.0740741</td>
<td style="text-align: right;">-0.8164966</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sam</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">73</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.713137</td>
<td style="text-align: right;">0.0185185</td>
<td style="text-align: right;">0.4082483</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tara</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">69</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-3</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.500000</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">-1.2247449</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Uma</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.635231</td>
<td style="text-align: right;">0.0740741</td>
<td style="text-align: right;">0.8164966</td>
</tr>
<tr class="even">
<td style="text-align: left;">Victor</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.713137</td>
<td style="text-align: right;">0.0185185</td>
<td style="text-align: right;">-0.4082483</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wendy</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.297341</td>
<td style="text-align: right;">0.2962963</td>
<td style="text-align: right;">1.6329932</td>
</tr>
<tr class="even">
<td style="text-align: left;">Xavier</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2.738613</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualizing-the-model-code" class="slide level2">
<h2>Visualizing the Model: Code</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="co"># Plot data points and predicted values</span></span>
<span id="cb9-2"><a href=""></a><span class="fu">ggplot</span>(engage_augmented, <span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">1</span>,</span>
<span id="cb9-3"><a href=""></a>                              <span class="at">y =</span> engagement)) <span class="sc">+</span></span>
<span id="cb9-4"><a href=""></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb9-5"><a href=""></a>  <span class="fu">geom_hline</span>(<span class="fu">aes</span>(<span class="at">yintercept =</span> .fitted[<span class="dv">1</span>]),</span>
<span id="cb9-6"><a href=""></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb9-7"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Engagement Score"</span>) <span class="sc">+</span></span>
<span id="cb9-8"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>) <span class="sc">+</span></span>
<span id="cb9-9"><a href=""></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-10"><a href=""></a>        <span class="at">axis.ticks.x =</span> <span class="fu">element_blank</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plot-intercept-only-model" class="slide level2">
<h2>Plot: Intercept-Only Model</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/intercept-augment-plot-1.png" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The red line shows ŷ (predicted value) for each person. But here the predicted value for everyone in the group is the same—the overall mean. Therefore the red line shows the group mean. The difference between each point and the line is the residual. The SD of the residuals is 2.58.</p>
</section>
<section id="why-is-it-the-mean-the-matrix-view" class="slide level2">
<h2>Why Is It the Mean? The Matrix View</h2>
<p><strong>Think of it as a spreadsheet, not scary math.</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/matrix-algebra-intercept.png" class="quarto-figure quarto-figure-center" style="width:80.0%;height:100.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>The X matrix is just a column of 1s. Everyone gets multiplied by the same weight (b₀)</li>
<li>So ŷ is the same for everyone: ŷ = b₀ × 1 = b₀</li>
</ul>
</section>
<section id="key-insight" class="slide level2 content-minimal">
<h2>Key Insight</h2>
<blockquote>
<p><strong>When everyone has the same predictor value, the best prediction is the group mean.</strong></p>
</blockquote>
<p>This is the foundation for everything that follows.</p>
<p>When we add categorical predictors, we’re essentially creating subgroups—and ŷ for each subgroup will be that subgroup’s mean.</p>
</section>
<section id="polling-question-1" class="slide level2 content-light">
<h2>Polling Question 1</h2>
<blockquote>
<p>If we run <code>lm(salary ~ 1)</code> on a dataset, what will the intercept represent?</p>
</blockquote>
<ul>
<li><ol type="A">
<li>Zero</li>
</ol></li>
<li><ol start="2" type="A">
<li>The mean salary</li>
</ol></li>
<li><ol start="3" type="A">
<li>The median salary</li>
</ol></li>
<li><ol start="4" type="A">
<li>The standard deviation of salary</li>
</ol></li>
</ul>
</section>
<section id="polling-question-1-answer" class="slide level2 content-light">
<h2>Polling Question 1: Answer</h2>
<p><strong>Correct answer: B) The mean salary</strong></p>
<p>When we run <code>lm(salary ~ 1)</code>, we’re fitting an intercept-only model with no predictors. The best single prediction for everyone is the mean of the outcome variable. The intercept captures this mean.</p>
</section>
<section id="from-one-group-to-many" class="slide level2 content-light">
<h2>From One Group to Many</h2>
<p>So far, we’ve predicted a single mean for everyone—treating all employees as one group.</p>
<p><strong>But in research, we usually want to compare groups:</strong></p>
<ul>
<li>Does turnover differ across <strong>departments</strong>?</li>
<li>Do outcomes differ between <strong>treatment</strong> and <strong>control</strong> conditions?</li>
<li>Does satisfaction vary by <strong>job type</strong>?</li>
</ul>
<p><strong>The goal:</strong> Give each group its <em>own</em> predicted mean (ŷ), so we can compare them. Think 1-way ANOVA with regression.</p>
<p><strong>The question:</strong> How do we tell the regression model which group each person belongs to?</p>
</section>
<section id="the-intuitive-approach" class="slide level2 content-light">
<h2>The Intuitive Approach</h2>
<p>A natural instinct is to create a column in your data that numbers the groups:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Employee</th>
<th>Department</th>
<th>Department Code</th>
<th>Turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Amy</td>
<td>HR</td>
<td>1</td>
<td>2.1</td>
</tr>
<tr class="even">
<td>Ben</td>
<td>Sales</td>
<td>2</td>
<td>3.5</td>
</tr>
<tr class="odd">
<td>Cara</td>
<td>Engineering</td>
<td>3</td>
<td>2.8</td>
</tr>
<tr class="even">
<td>Dan</td>
<td>HR</td>
<td>1</td>
<td>1.9</td>
</tr>
</tbody>
</table>
<p>Then use <code>lm(turnover ~ department_code)</code>.</p>
<p><strong>This feels sensible—but it creates serious problems.</strong></p>
</section>
<section id="why-cant-we-just-use-1-2-3-for-groups" class="slide level2 content-light">
<h2>Why Can’t We Just Use 1, 2, 3 for Groups?</h2>
<p>Students often think they can code groups as 1, 2, 3 and use that column directly.</p>
<p><strong>The problem:</strong> The coefficient would represent “for every 1-unit increase in department number, turnover increases by X”</p>
<ul>
<li>But what does it mean to “increase by 1 department”?</li>
<li>This implies Sales is exactly “between” HR and Engineering</li>
<li>Departments aren’t ordered—there’s no meaningful “distance” between them</li>
</ul>
</section>
<section id="the-arbitrary-ordering-problem" class="slide level2 content-light">
<h2>The Arbitrary Ordering Problem</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coding Option</th>
<th>HR</th>
<th>Sales</th>
<th>Engineering</th>
<th>Implied Order</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Option A</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>HR &lt; Sales &lt; Eng</td>
</tr>
<tr class="even">
<td>Option B</td>
<td>1</td>
<td>3</td>
<td>2</td>
<td>HR &lt; Eng &lt; Sales</td>
</tr>
<tr class="odd">
<td>Option C</td>
<td>2</td>
<td>1</td>
<td>3</td>
<td>Sales &lt; HR &lt; Eng</td>
</tr>
</tbody>
</table>
<p>Each coding gives different regression coefficients! The overall model fit (R², F-test) stays the same, but the coefficients have different meanings.</p>
</section>
<section id="measurement-levels" class="slide level2 content-light">
<h2>Measurement Levels</h2>
<table class="caption-top">
<colgroup>
<col style="width: 15%">
<col style="width: 19%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th>Level</th>
<th>Example</th>
<th>Can we use numbers directly?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nominal</td>
<td>Department, Gender, Treatment group</td>
<td>No—no ordering exists</td>
</tr>
<tr class="even">
<td>Ordinal</td>
<td>Education level (HS, BA, MA, PhD)</td>
<td>Ordering exists but intervals unequal</td>
</tr>
<tr class="odd">
<td>Interval</td>
<td>Temperature, Test scores</td>
<td>Yes—equal intervals meaningful</td>
</tr>
</tbody>
</table>
<p><strong>Departments are nominal</strong>—using 1, 2, 3 pretends they’re interval-level data.</p>
</section>
<section id="what-goes-wrong-a-demonstration" class="slide level2">
<h2>What Goes Wrong: A Demonstration</h2>
<p>Suppose we have three departments with these mean turnover rates:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Department</th>
<th>Mean Turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HR</td>
<td>2.0</td>
</tr>
<tr class="even">
<td>Sales</td>
<td>3.3</td>
</tr>
<tr class="odd">
<td>Engineering</td>
<td>3.0</td>
</tr>
</tbody>
</table>
<p>If we code them as 1, 2, 3 and run regression, we get ONE coefficient that says: “For each +1 in department number, turnover changes by X.”</p>
<p><strong>But which ordering should we use?</strong></p>
<ul>
<li>HR=1, Sales=2, Eng=3 → coefficient = +0.5</li>
<li>HR=1, Eng=2, Sales=3 → coefficient = +0.65</li>
<li>Sales=1, HR=2, Eng=3 → coefficient = -0.15</li>
</ul>
<p><strong>Same data, different answers!</strong> The coefficient depends on an arbitrary choice.</p>
</section>
<section id="the-real-problem" class="slide level2 content-light">
<h2>The Real Problem</h2>
<p>Using 1, 2, 3 assumes:</p>
<ol type="1">
<li>The groups are <strong>ordered</strong> (they’re not)</li>
<li>The <strong>distance</strong> between 1→2 equals 2→3 (meaningless)</li>
<li>The effect is <strong>linear</strong> across this fake scale (nonsense)</li>
</ol>
<p><strong>We need a coding system that:</strong></p>
<ul>
<li>Doesn’t impose a fake ordering</li>
<li>Lets each group have its own mean</li>
<li>Makes interpretable comparisons</li>
</ul>
<p>That’s what <strong>contrast coding</strong> does!</p>
</section>
<section id="the-solution-contrast-coding" class="slide level2 content-minimal">
<h2>The Solution: Contrast Coding</h2>
<p>Instead of one column with arbitrary numbers, we create multiple columns of 0s and 1s that capture group membership without imposing false assumptions.</p>
<p>We’ll start with <strong>treatment coding</strong> (also called dummy coding).</p>
</section>
<section id="part-2-treatment-coding-with-two-groups" class="slide level2 section-header" data-background="linear-gradient(135deg, #e65100 0%, #ef6c00 50%, #f57c00 100%)">
<h2>Part 2: Treatment Coding with Two Groups</h2>
</section>
<section id="section-2" class="slide level2" data-background-image="images/ai-image-2.png" data-background-size="cover">
<h2></h2>
<div class="overlay-text-bottom">
<p><strong>Scenario:</strong> Remote work vs.&nbsp;in-office—who’s more satisfied?</p>
</div>
</section>
<section id="remote-vs.-in-office-the-research-question" class="slide level2 content-light">
<h2>Remote vs.&nbsp;In-Office: The Research Question</h2>
<p>A company wants to compare job satisfaction between remote and in-office workers.</p>
<p><strong>This is exactly the situation where you might run a t-test.</strong></p>
<p>But regression gives us the same answer—in a more flexible framework that we can build on.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Approach</th>
<th>What it tells us</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>t-test</td>
<td>Are the means different?</td>
</tr>
<tr class="even">
<td>Regression</td>
<td>Are the means different? (same answer!)</td>
</tr>
<tr class="odd">
<td>Regression advantage</td>
<td>Easily extends to multiple predictors</td>
</tr>
</tbody>
</table>
</section>
<section id="work-location-data" class="slide level2">
<h2>Work Location Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href=""></a>work_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/work_location_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: left;">location</th>
<th style="text-align: right;">satisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alex</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">70</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beth</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carl</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">71</td>
</tr>
<tr class="even">
<td style="text-align: left;">Derek</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emma</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">68</td>
</tr>
<tr class="even">
<td style="text-align: left;">Felix</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dana</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">82</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eric</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">78</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fran</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gina</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">84</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hugo</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Irene</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="setting-up-the-factor" class="slide level2">
<h2>Setting Up the Factor</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href=""></a>work_data <span class="ot">&lt;-</span> work_data <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">location =</span> <span class="fu">as.factor</span>(location)) <span class="sc">|&gt;</span></span>
<span id="cb11-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">location =</span> <span class="fu">fct_relevel</span>(location, <span class="st">"office"</span>))</span>
<span id="cb11-4"><a href=""></a></span>
<span id="cb11-5"><a href=""></a><span class="fu">levels</span>(work_data<span class="sc">$</span>location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "office" "remote"</code></pre>
</div>
</div>
<p>The output shows <code>"office" "remote"</code>. See how “office” comes first? That means it’s our reference group—the one that gets 0s in the contrast column.</p>
<ul>
<li>First convert the text column to a factor</li>
<li>Then explicitly set “office” as the reference group</li>
<li>The reference group is the baseline we compare against</li>
</ul>
</section>
<section id="understanding-the-reference-group" class="slide level2">
<h2>Understanding the Reference Group</h2>
<p><strong>The reference group isn’t “better” or “special”—it’s just our comparison point.</strong></p>
<p>We could pick any group. It’s like choosing which city to measure distances from. If you measure from Toronto, Guelph is about 100 km away. If you measure from Vancouver, Guelph is about 4,300 km away. The cities haven’t moved—just your reference point.</p>
<div title="Pro Tip: The Model Stays the Same">
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Pro Tip: The Model Stays the Same</strong></p>
</div>
<div class="callout-content">
<p>Changing the reference group changes the <strong>coefficients</strong> (because the comparison point moves), but it does <strong>NOT</strong> change the model fit (<span class="math inline">\(R^2\)</span>) or the predicted values (<span class="math inline">\(\hat{y}\)</span>) for any group. The model makes the same predictions regardless of which group you call “reference.”</p>
<p><em>Note:</em> With unequal group sizes, the choice of reference group can affect standard errors and significance—more on this later.</p>
</div>
</div>
</div>
</div>
</section>
<section id="factor-functions-comparison" class="slide level2 content-light">
<h2>Factor Functions Comparison</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 22%">
<col style="width: 48%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Function</th>
<th>Reference group order</th>
<th>When to use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>as.factor()</code></td>
<td>Alphabetical</td>
<td>When alphabetical makes sense</td>
</tr>
<tr class="even">
<td><code>as_factor()</code></td>
<td>Order in data</td>
<td>When data order is meaningful</td>
</tr>
<tr class="odd">
<td><code>fct_relevel()</code></td>
<td>You choose explicitly</td>
<td><strong>Recommended!</strong> Always be explicit</td>
</tr>
</tbody>
</table>
</section>
<section id="how-r-builds-the-design-matrix" class="slide level2">
<h2>How R Builds the Design Matrix</h2>
<p>When you have a factor with 2 levels, R creates:</p>
<ul>
<li>Column 1: All 1s (the intercept column, labeled “Int”)</li>
<li>Column 2: 0 for reference group, 1 for other group (the contrast column, labeled “c1”)</li>
</ul>
<p><strong>New notation:</strong> “Int” = intercept column (always 1s). “c1” = contrast column 1 (0s and 1s that identify group membership). We’ll add c2, c3, etc. when we have more groups.</p>
<pre><code>Employee  Location   y    Int   c1
------------------------------------
Alex      office     70    1     0
Beth      office     74    1     0
Carl      office     71    1     0
...
Dana      remote     82    1     1
Eric      remote     78    1     1
Fran      remote     80    1     1</code></pre>
</section>
<section id="design-matrix-y-xb" class="slide level2">
<h2>Design Matrix: y = Xb</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/matrix-algebra-location.png" class="quarto-figure quarto-figure-center" style="width:80.0%;height:100.0%"></p>
</figure>
</div>
</div>
</div>
<div class="smaller">
<p>The <strong>design matrix (X)</strong> is the complete set of predictor columns that R uses to calculate predictions. It combines:</p>
<ul>
<li>The <strong>intercept column</strong> (all 1s)—ensures everyone starts with a baseline value</li>
<li>The <strong>contrast column(s)</strong>—the 0/1 codes that identify group membership</li>
</ul>
</div>
</section>
<section id="key-points-treatment-coding" class="slide level2 content-light">
<h2>Key Points: Treatment Coding</h2>
<ul>
<li>Reference group gets <strong>0</strong> on the contrast column</li>
<li>Other group gets <strong>1</strong> on the contrast column</li>
<li>Everyone gets <strong>1</strong> on the intercept column</li>
<li>The 0/1 pattern “turns on/off” the coefficient</li>
</ul>
</section>
<section id="the-light-switch-analogy" class="slide level2 content-light">
<h2>The Light Switch Analogy</h2>
<p><strong>Notation:</strong> b₁ is the coefficient for the first contrast column (c1). It tells us how much to add when c1 = 1.</p>
<p>Think of each coefficient as a light with a switch:</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>c1 value</th>
<th>What it does</th>
<th>Like a light switch…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>0</strong></td>
<td>The term contributes <strong>nothing</strong> (8 × 0 = 0)</td>
<td>Switch is off</td>
</tr>
<tr class="even">
<td><strong>1</strong></td>
<td>The term <strong>adds its value</strong> (8 × 1 = 8)</td>
<td>Switch is on</td>
</tr>
</tbody>
</table>
<p>The coefficient itself (8) never changes—it’s the multiplication by 0 or 1 that determines if it contributes.</p>
</section>
<section id="light-switch-diagram" class="slide level2">
<h2>Light Switch Diagram</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/light-switch-diagram-1.png" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="running-the-regression" class="slide level2">
<h2>Running the Regression</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a>lm_location <span class="ot">&lt;-</span> <span class="fu">lm</span>(satisfaction <span class="sc">~</span> location, <span class="at">data =</span> work_data)</span>
<span id="cb14-2"><a href=""></a><span class="fu">tidy</span>(lm_location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">1.140175</td>
<td style="text-align: right;">63.148177</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">locationremote</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.612451</td>
<td style="text-align: right;">4.961389</td>
<td style="text-align: right;">0.0005689</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The intercept (72) is the mean for office workers—because that was our reference level. Remember <code>fct_relevel(location, "office")</code>?</p>
<p>The coefficient for <code>locationremote</code> (8) is the difference between the remote mean and the office mean. So the mean for remote workers is 80 (72 + 8 = 80).</p>
<p>The p-value for <code>locationremote</code> tests whether the means differ between groups.</p>
<p><strong>What does p = 0.0005689 mean?</strong> If office and remote workers were actually the same, we’d have only a 0.057% chance of seeing a difference this large or larger. That’s very unlikely—so we’re confident the groups truly differ.</p>
</section>
<section id="augment-the-data-1" class="slide level2">
<h2>Augment the Data</h2>
<p>Make predicted scores for each person/group</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>work_augmented <span class="ot">&lt;-</span> <span class="fu">augment</span>(lm_location, <span class="at">data =</span> work_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell augment">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 6%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: left;">location</th>
<th style="text-align: right;">satisfaction</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.resid</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alex</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.851900</td>
<td style="text-align: right;">0.0615385</td>
<td style="text-align: right;">-0.7844645</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beth</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.851900</td>
<td style="text-align: right;">0.0615385</td>
<td style="text-align: right;">0.7844645</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carl</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-1</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.921187</td>
<td style="text-align: right;">0.0153846</td>
<td style="text-align: right;">-0.3922323</td>
</tr>
<tr class="even">
<td style="text-align: left;">Derek</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.732520</td>
<td style="text-align: right;">0.1384615</td>
<td style="text-align: right;">1.1766968</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Emma</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">68</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">-4</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.556039</td>
<td style="text-align: right;">0.2461538</td>
<td style="text-align: right;">-1.5689291</td>
</tr>
<tr class="even">
<td style="text-align: left;">Felix</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">office</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.851900</td>
<td style="text-align: right;">0.0615385</td>
<td style="text-align: right;">0.7844645</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dana</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.851900</td>
<td style="text-align: right;">0.0615385</td>
<td style="text-align: right;">0.7844645</td>
</tr>
<tr class="even">
<td style="text-align: left;">Eric</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">-2</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.851900</td>
<td style="text-align: right;">0.0615385</td>
<td style="text-align: right;">-0.7844645</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fran</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.943920</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gina</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">84</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.556039</td>
<td style="text-align: right;">0.2461538</td>
<td style="text-align: right;">1.5689291</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hugo</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">76</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">-4</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.556039</td>
<td style="text-align: right;">0.2461538</td>
<td style="text-align: right;">-1.5689291</td>
</tr>
<tr class="even">
<td style="text-align: left;">Irene</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.1666667</td>
<td style="text-align: right;">2.943920</td>
<td style="text-align: right;">0.0000000</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualizing-the-model-result" class="slide level2">
<h2>Visualizing the Model: Result</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href=""></a><span class="co"># Create augmented data with predictions and residuals</span></span>
<span id="cb16-2"><a href=""></a><span class="fu">ggplot</span>(work_augmented, <span class="fu">aes</span>(<span class="at">x =</span> location,</span>
<span id="cb16-3"><a href=""></a>                           <span class="at">y =</span> satisfaction,</span>
<span id="cb16-4"><a href=""></a>                           <span class="at">group =</span> location)) <span class="sc">+</span></span>
<span id="cb16-5"><a href=""></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb16-6"><a href=""></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .fitted, <span class="at">ymax =</span> .fitted), </span>
<span id="cb16-7"><a href=""></a>                <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Work Location"</span>, <span class="at">y =</span> <span class="st">"Job Satisfaction"</span>) <span class="sc">+</span></span>
<span id="cb16-9"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plot-work-location-model" class="slide level2">
<h2>Plot: Work Location Model</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/location-augment-plot-1.png" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The lines show ŷ (predicted values) for each group—which equal the group means!</p>
</section>
<section id="interpreting-the-output" class="slide level2 content-light">
<h2>Interpreting the Output</h2>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 32%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>What it means</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>(Intercept)</code></td>
<td>72</td>
<td>Mean satisfaction for <strong>office</strong> workers (reference group)</td>
</tr>
<tr class="even">
<td><code>locationremote</code></td>
<td>8</td>
<td><strong>Difference</strong>: remote mean − office mean</td>
</tr>
</tbody>
</table>
<ul>
<li>The intercept (72) is the mean for the reference group—office workers</li>
<li>The coefficient (8) tells us remote workers score 8 points higher on average</li>
<li>So the remote mean is 72 + 8 = 80</li>
</ul>
</section>
<section id="quick-check" class="slide level2 content-light">
<h2>Quick Check</h2>
<blockquote>
<p><strong>Before moving on:</strong> In your own words, what does the coefficient of 8 tell us?</p>
</blockquote>
<p>Take a moment to think about this—it’s the key to interpreting treatment-coded regression.</p>
</section>
<section id="verify-with-group-means" class="slide level2">
<h2>Verify with Group Means</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href=""></a>work_data <span class="sc">|&gt;</span></span>
<span id="cb17-2"><a href=""></a>  <span class="fu">group_by</span>(location) <span class="sc">|&gt;</span></span>
<span id="cb17-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">mean_satisfaction =</span> <span class="fu">mean</span>(satisfaction))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">location</th>
<th style="text-align: right;">mean_satisfaction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">office</td>
<td style="text-align: right;">72</td>
</tr>
<tr class="even">
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Intercept = office mean. Coefficient = difference between means.</p>
</section>
<section id="connection-to-the-t-test" class="slide level2">
<h2>Connection to the t-Test</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href=""></a><span class="fu">t.test</span>(satisfaction <span class="sc">~</span> location, <span class="at">data =</span> work_data, <span class="at">var.equal =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  satisfaction by location
t = -4.9614, df = 10, p-value = 0.0005689
alternative hypothesis: true difference in means between group office and group remote is not equal to 0
95 percent confidence interval:
 -11.592766  -4.407234
sample estimates:
mean in group office mean in group remote 
                  72                   80 </code></pre>
</div>
</div>
<p>Same p-value as the regression (<strong>p = 0.0005689</strong>)! Regression with a 2-level factor IS an independent samples t-test.</p>
<p><strong>Why <code>var.equal = TRUE</code>?</strong> We use this option because regression assumes equal variances across groups (homoscedasticity). The default Welch t-test relaxes this assumption and would give slightly different results. With <code>var.equal = TRUE</code>, the t-test uses a pooled variance estimate—exactly what regression does.</p>
</section>
<section id="running-the-regression-redux" class="slide level2">
<h2>Running the Regression: Redux</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href=""></a>lm_location <span class="ot">&lt;-</span> <span class="fu">lm</span>(satisfaction <span class="sc">~</span> location, <span class="at">data =</span> work_data)</span>
<span id="cb20-2"><a href=""></a><span class="fu">tidy</span>(lm_location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">1.140175</td>
<td style="text-align: right;">63.148177</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">locationremote</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.612451</td>
<td style="text-align: right;">4.961389</td>
<td style="text-align: right;">0.0005689</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The intercept (72) is the mean for office workers—because that was our reference level. Remember <code>fct_relevel(location, "office")</code>?</p>
<p>The coefficient for <code>locationremote</code> (8) is the difference between the remote mean and the office mean. So the mean for remote workers is 80 (72 + 8 = 80).</p>
<p>The p-value for <code>locationremote</code> tests whether the means differ between groups.</p>
<p><strong>What does p = 0.0005689 mean?</strong> If office and remote workers were actually the same, we’d have only a 0.057% chance of seeing a difference this large or larger. That’s very unlikely—so we’re confident the groups truly differ.</p>
</section>
<section id="the-three-quantities-you-must-distinguish" class="slide level2 content-light">
<h2>The Three Quantities You Must Distinguish</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/three-quantities-visual-1.png" class="quarto-figure quarto-figure-center" width="864"></p>
</figure>
</div>
</div>
</div>
<p><strong>The coefficient is NOT the group mean—it’s the DIFFERENCE from the reference group!</strong></p>
</section>
<section id="common-mistake-to-avoid" class="slide level2 content-light">
<h2>Common Mistake to Avoid</h2>
<p><strong>A student writes:</strong> “Remote workers have a satisfaction score of 8.”</p>
<p><strong>What’s wrong?</strong> The coefficient (8) is the <em>difference</em> between groups, not the remote group’s mean!</p>
<table class="caption-top">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>What they wrote</th>
<th>What they should write</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>“Remote satisfaction = 8”</td>
<td>“Remote satisfaction = 80 (intercept + coefficient = 72 + 8)”</td>
</tr>
<tr class="even">
<td>“The remote effect is 80”</td>
<td>“The remote effect is 8 points higher than office”</td>
</tr>
</tbody>
</table>
<p><strong>Remember:</strong></p>
<ul>
<li>The <strong>intercept</strong> (72) = reference group mean</li>
<li>The <strong>coefficient</strong> (8) = how much higher/lower the other group is</li>
<li>The <strong>other group’s mean</strong> = intercept + coefficient (72 + 8 = 80)</li>
</ul>
</section>
<section id="polling-question-2" class="slide level2 content-light">
<h2>Polling Question 2</h2>
<p><strong>The regression output:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">21.43</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">0.0012000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">-3</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">0.3256000</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li><p>Type the mean for <strong>Engineering</strong> in the chat…</p></li>
<li><p><strong>DO NOT PRESS ENTER YET!</strong></p></li>
<li><p>Wait for my signal…</p></li>
</ol>
</section>
<section id="practice-answers" class="slide level2 content-light">
<h2>Practice: Answers</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">45</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">21.43</td>
<td style="text-align: right;">0.0000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">4.00</td>
<td style="text-align: right;">0.0012000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">-3</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">-1.00</td>
<td style="text-align: right;">0.3256000</td>
</tr>
</tbody>
</table>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Question</th>
<th>Answer</th>
<th>Explanation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Reference group?</td>
<td><strong>HR</strong></td>
<td>It doesn’t appear as a coefficient</td>
</tr>
<tr class="even">
<td>HR mean?</td>
<td><strong>45</strong></td>
<td>Reference mean = intercept</td>
</tr>
<tr class="odd">
<td>Sales mean?</td>
<td><strong>45 + 12 = 57</strong></td>
<td>Intercept + coefficient</td>
</tr>
<tr class="even">
<td>Engineering mean?</td>
<td><strong>45 + (-3) = 42</strong></td>
<td>Intercept + coefficient</td>
</tr>
</tbody>
</table>
<p><strong>Key insight:</strong> Engineering’s <em>negative</em> coefficient means they score <em>lower</em> than HR.</p>
</section>
<section id="thinking-horizontally-predicted-scores" class="slide level2 content-light">
<h2>Thinking Horizontally: Predicted Scores</h2>
<p>For each person, we calculate ŷ by:</p>
<ol type="1">
<li>Reading across their row in the design matrix</li>
<li>Multiplying each value by its coefficient</li>
<li>Adding up all the products</li>
</ol>
</section>
<section id="matrices-thinking-horizontally-visual" class="slide level2">
<h2>Matrices: Thinking Horizontally Visual</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/thinking-horizontally-diagram-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p>Because Dana is a remote worker the c1 value is 1 for her.</p>
<div style="font-size: 0.6em;">
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">1.140175</td>
<td style="text-align: right;">63.148177</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">locationremote</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">1.612451</td>
<td style="text-align: right;">4.961389</td>
<td style="text-align: right;">0.0005689</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="the-prediction-equation" class="slide level2 content-light">
<h2>The Prediction Equation</h2>
<p>For our model: ŷ = b₀(Int) + b₁(c1) = 72(Int) + 8(c1)</p>
<p>Where:</p>
<ul>
<li>b₀ = 72 (intercept)</li>
<li>b₁ = 8 (coefficient for remote)</li>
<li>Int = intercept column value (always 1)</li>
<li>c1 = contrast column value (0 for office, 1 for remote)</li>
</ul>
</section>
<section id="full-calculation-table" class="slide level2 content-light">
<h2>Full Calculation Table</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Name</th>
<th>Location</th>
<th>y</th>
<th>Int</th>
<th>c1</th>
<th>ŷ Calculation</th>
<th>ŷ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Alex</td>
<td>office</td>
<td>70</td>
<td>1</td>
<td>0</td>
<td>72(1) + 8(0) = 72 + 0</td>
<td><strong>72</strong></td>
</tr>
<tr class="even">
<td>Beth</td>
<td>office</td>
<td>74</td>
<td>1</td>
<td>0</td>
<td>72(1) + 8(0) = 72 + 0</td>
<td><strong>72</strong></td>
</tr>
<tr class="odd">
<td>Carl</td>
<td>office</td>
<td>71</td>
<td>1</td>
<td>0</td>
<td>72(1) + 8(0) = 72 + 0</td>
<td><strong>72</strong></td>
</tr>
<tr class="even">
<td>Dana</td>
<td>remote</td>
<td>82</td>
<td>1</td>
<td>1</td>
<td>72(1) + 8(1) = 72 + 8</td>
<td><strong>80</strong></td>
</tr>
<tr class="odd">
<td>Eric</td>
<td>remote</td>
<td>78</td>
<td>1</td>
<td>1</td>
<td>72(1) + 8(1) = 72 + 8</td>
<td><strong>80</strong></td>
</tr>
<tr class="even">
<td>Fran</td>
<td>remote</td>
<td>80</td>
<td>1</td>
<td>1</td>
<td>72(1) + 8(1) = 72 + 8</td>
<td><strong>80</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="step-by-step-calculating-ŷ-for-dana" class="slide level2 content-light">
<h2>Step-by-Step: Calculating ŷ for Dana</h2>
<p>Let’s walk through Dana’s calculation slowly:</p>
<ol type="1">
<li><p><strong>Find Dana’s row values:</strong> Int = 1, c1 = 1</p></li>
<li><p><strong>Multiply each by its coefficient:</strong></p>
<ul>
<li>Intercept: 72 × 1 = 72</li>
<li>Remote coefficient: 8 × 1 = 8</li>
</ul></li>
<li><p><strong>Add the products:</strong> 72 + 8 = <strong>80</strong></p></li>
</ol>
<p><strong>Why does c1 = 1 matter?</strong> It “turns on” the remote coefficient, adding 8 to the intercept!</p>
</section>
<section id="the-key-insight" class="slide level2 content-light">
<h2>The Key Insight</h2>
<blockquote>
<p><strong>The 0 or 1 acts like an on/off switch for the coefficient!</strong></p>
</blockquote>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>Contrast value</th>
<th>Effect on ŷ</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Office (reference)</td>
<td>0</td>
<td>Coefficient is <strong>OFF</strong> → ŷ = intercept only</td>
</tr>
<tr class="even">
<td>Remote</td>
<td>1</td>
<td>Coefficient is <strong>ON</strong> → ŷ = intercept + coefficient</td>
</tr>
</tbody>
</table>
</section>
<section id="your-turn-calculate-ŷ-for-beth" class="slide level2 content-light">
<h2>Your Turn: Calculate ŷ for Beth</h2>
<p>Beth is an <strong>office</strong> worker. Using the same model (b₀ = 72, b₁ = 8):</p>
<p><strong>Step 1:</strong> What are Beth’s row values?</p>
<ul>
<li>Int = ?</li>
<li>c1 = ?</li>
</ul>
<p><strong>Step 2:</strong> Write the equation and plug in values</p>
<p><strong>Step 3:</strong> Calculate ŷ</p>
<p>⏱️ Take 60 seconds. When ready, put your answer in the chat. I’ll reveal the solution after.</p>
</section>
<section id="your-turn-answer" class="slide level2 content-light">
<h2>Your Turn: Answer</h2>
<p>Beth is an <strong>office</strong> worker (reference group).</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Step</th>
<th>What we do</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Find Beth’s row values</td>
<td>Int = 1, c1 = <strong>0</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td>Write equation with values</td>
<td>ŷ = 72(1) + 8(<strong>0</strong>)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Calculate</td>
<td>72 + 0 = <strong>72</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key point:</strong> Because c1 = 0, the remote coefficient is “switched off.” Beth only gets the intercept!</p>
</section>
<section id="the-calculation-template" class="slide level2 content-light">
<h2>The Calculation Template</h2>
<p>Use this for ANY treatment-coded regression:</p>
<blockquote>
<p><strong>Step 1:</strong> Find their row (what are their 0s and 1s?)</p>
<p><strong>Step 2:</strong> Write: ŷ = b₀(Int) + b₁(c1) + b₂(c2) + …</p>
<p><strong>Step 3:</strong> Plug in their values</p>
<p><strong>Step 4:</strong> Multiply first, then add</p>
</blockquote>
<p><strong>Pro tip:</strong> If they’re in the reference group, all contrast columns = 0, so ŷ = intercept.</p>
</section>
<section id="connecting-back-to-ŷ-as-group-mean" class="slide level2 content-light">
<h2>Connecting Back to ŷ as Group Mean</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Group</th>
<th>ŷ</th>
<th>Actual mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Office (reference)</td>
<td>72</td>
<td>72</td>
</tr>
<tr class="even">
<td>Remote</td>
<td>80</td>
<td>80</td>
</tr>
</tbody>
</table>
<p><strong>The predicted value for everyone in a group is that group’s mean!</strong></p>
<p>This is the connection to Part 1: ŷ estimates the conditional mean.</p>
</section>
<section id="ready-for-more-groups" class="slide level2 content-light">
<h2>Ready for More Groups?</h2>
<p><strong>Good news:</strong> Everything we just learned applies to more than two groups!</p>
<p>The only change: We add more contrast columns—one for each additional group beyond the reference.</p>
<p>With 2 groups → 1 contrast column (what we just did)</p>
<p>With 4 groups → 3 contrast columns (coming up next)</p>
<p>The a-1 rule tells us exactly how many we need.</p>
</section>
<section id="additional-statistics-for-results-part-1" class="slide level2">
<h2>Additional Statistics for Results Part 1</h2>
<div style="font-size: 0.75em;">
<p>Beyond coefficients and p-values, APA 7 requires effect sizes and model fit statistics.</p>
<p><strong>R² from glance():</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href=""></a><span class="fu">glance</span>(lm_location)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 2%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.7111111</td>
<td style="text-align: right;">0.6822222</td>
<td style="text-align: right;">2.792848</td>
<td style="text-align: right;">24.61538</td>
<td style="text-align: right;">0.0005689</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">-28.25808</td>
<td style="text-align: right;">62.51615</td>
<td style="text-align: right;">63.97087</td>
<td style="text-align: right;">78</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">12</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>R² Confidence Interval from MBESS:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href=""></a>MBESS<span class="sc">::</span><span class="fu">ci.R2</span>(<span class="at">R2 =</span> <span class="fl">0.71</span>, <span class="at">N =</span> <span class="dv">12</span>, <span class="at">K =</span> <span class="dv">1</span>, <span class="at">Random.Regressors =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: right;">R2</th>
<th style="text-align: right;">CI_lower</th>
<th style="text-align: right;">CI_upper</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.71</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.84</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="additional-statistics-for-results-part-2" class="slide level2">
<h2>Additional Statistics for Results Part 2</h2>
<div style="font-size: 0.75em;">
<p><strong>Cohen’s d from effsize package:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href=""></a><span class="fu">cohen.d</span>(satisfaction <span class="sc">~</span> location, <span class="at">data =</span> work_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Cohen's d

d estimate: -2.864459 (large)
95 percent confidence interval:
    lower     upper 
-4.695352 -1.033567 </code></pre>
</div>
</div>
<p><strong>Descriptive Statistics:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href=""></a>work_data <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href=""></a>  <span class="fu">group_by</span>(location) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">mean_satisfaction =</span> <span class="fu">mean</span>(satisfaction),</span>
<span id="cb25-4"><a href=""></a>            <span class="at">sd_satisfaction =</span> <span class="fu">sd</span>(satisfaction),</span>
<span id="cb25-5"><a href=""></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">location</th>
<th style="text-align: right;">mean_satisfaction</th>
<th style="text-align: right;">sd_satisfaction</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">office</td>
<td style="text-align: right;">72</td>
<td style="text-align: right;">2.756810</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">remote</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">2.828427</td>
<td style="text-align: right;">6</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="results-paragraph-work-location" class="slide level2 results-paragraph">
<h2>Results Paragraph: Work Location</h2>
<div style="font-size: 0.85em;">
<p>We examined whether work location (office vs.&nbsp;remote) was associated with job satisfaction (<em>N</em> = 12). We used linear regression with treatment coding, where office workers served as the reference group.</p>
<p><strong>Descriptive statistics.</strong> Office workers (<em>n</em> = 6) had a mean job satisfaction of 72.00 (<em>SD</em> = 2.76). Remote workers (<em>n</em> = 6) had a mean job satisfaction of 80.00 (<em>SD</em> = 2.83).</p>
<p><strong>Results.</strong> The regression coefficient (<em>b</em>) represents how much higher (or lower) remote workers’ satisfaction is compared to office workers. Remote workers scored 8.00 points higher than office workers, <em>b</em> = 8.00, 95% CI [4.41, 11.59], <em>t</em>(10) = 4.96, <em>p</em> &lt; .001. This difference corresponds to a large effect, <em>d</em> = 2.86, 95% CI [1.03, 4.70]. The model explained 71.1% of the variance in job satisfaction, <em>R</em>² = .71, 95% CI [.25, .84].</p>
</div>
</section>
<section id="part-2-summary-two-group-treatment-coding" class="slide level2 content-light">
<h2>Part 2 Summary: Two-Group Treatment Coding</h2>
<table class="caption-top">
<colgroup>
<col style="width: 28%">
<col style="width: 43%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>What It Means</th>
<th>Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Reference group</strong></td>
<td>The group coded as 0; serves as the comparison baseline</td>
<td>Office workers</td>
</tr>
<tr class="even">
<td><strong>Intercept (b₀)</strong></td>
<td>Mean of the reference group</td>
<td>72 = Office mean</td>
</tr>
<tr class="odd">
<td><strong>Coefficient (b₁)</strong></td>
<td>Difference between groups (other − reference)</td>
<td>8 = Remote is 8 points higher</td>
</tr>
<tr class="even">
<td><strong>Other group mean</strong></td>
<td>Intercept + Coefficient</td>
<td>72 + 8 = 80</td>
</tr>
<tr class="odd">
<td><strong>p-value for coefficient</strong></td>
<td>Tests if the group difference is significant</td>
<td>p &lt; .001 → groups differ</td>
</tr>
</tbody>
</table>
<p><strong>Quick reference:</strong> To get any group’s mean, add the intercept to that group’s coefficient. The reference group’s coefficient is 0 (not shown), so its mean = intercept.</p>
</section>
<section id="part-3-multiple-groups" class="slide level2 section-header" data-background="linear-gradient(135deg, #1b5e20 0%, #2e7d32 50%, #388e3c 100%)">
<h2>Part 3: Multiple Groups</h2>
</section>
<section id="treatment-coding-with-4-levels" class="slide level2 content-minimal" data-background-image="images/ai-image-3.png" data-background-size="contain" data-background-opacity="0.99" data-background-position="center 60%">
<h2>Treatment Coding with 4 Levels</h2>
<p>Same logic, just more contrast columns. The a-1 rule applies.</p>
</section>
<section id="the-a-1-rule" class="slide level2">
<h2>The a-1 Rule</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th># of groups (a)</th>
<th># of contrast columns</th>
<th>Why?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2</td>
<td>1</td>
<td>Reference captured by intercept</td>
</tr>
<tr class="even">
<td>3</td>
<td>2</td>
<td>Reference captured by intercept</td>
</tr>
<tr class="odd">
<td>4</td>
<td>3</td>
<td>Reference captured by intercept</td>
</tr>
<tr class="even">
<td>a</td>
<td>a-1</td>
<td>Reference captured by intercept</td>
</tr>
</tbody>
</table>
<p><strong>Rule:</strong> a groups need a-1 contrast columns. The reference group is identified by having zeros on ALL contrast columns.</p>
<p><strong>Why does this work?</strong> Think of it like 4 rooms. If someone says “I’m not in Room 1, not in Room 2, not in Room 3”—you know they’re in Room 4 by elimination. The reference group is identified the same way: all 0s means “none of the above” = reference group.</p>
<p><strong>Important implication:</strong> This is why your regression output never shows a coefficient for the reference group—there IS no column for it! The reference group’s mean is captured entirely by the intercept.</p>
</section>
<section id="quick-prediction" class="slide level2 content-light">
<h2>Quick Prediction</h2>
<blockquote>
<p>With 4 groups, how many contrast columns do you think R will create?</p>
</blockquote>
<p>Type your answer in the chat—don’t press enter yet!</p>
<p>Think about the a-1 rule we just learned…</p>
</section>
<section id="the-a-1-rule-contr.treatment4" class="slide level2">
<h2>The a-1 Rule: contr.treatment(4)</h2>
<p>We can see the contrast coding for 4 groups with <code>contr.treatment(4)</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href=""></a><span class="fu">contr.treatment</span>(<span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  2 3 4
1 0 0 0
2 1 0 0
3 0 1 0
4 0 0 1</code></pre>
</div>
</div>
<p><strong>Reading the output:</strong></p>
<ul>
<li><strong>Row labels (1, 2, 3, 4):</strong> Represent the four groups. Everyone in group 1 receives the contrast values from row 1; everyone in group 2 receives the values from row 2, and so on.</li>
<li><strong>Column labels (2, 3, 4):</strong> These are numbered starting at 2 because the intercept is implicitly column 1 in the full design matrix. This output shows only the contrast columns.</li>
</ul>
<p><strong>Interpretation:</strong> Group 1 (the reference) has all zeros—their predicted value comes entirely from the intercept. Groups 2, 3, and 4 each have a single “1” in their respective column, indicating their coefficient represents the difference from the reference group.</p>
</section>
<section id="the-a-1-rule-visual" class="slide level2">
<h2>The a-1 Rule: Visual</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/a-minus-1-visual-1.png" class="quarto-figure quarto-figure-center" width="864"></p>
</figure>
</div>
</div>
</div>
<p>You can see HR is the reference group meaning we used: department = fct_relevel(department, “HR”)</p>
</section>
<section id="department-data" class="slide level2">
<h2>Department Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href=""></a>dept_data <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"../data/department_data.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: left;">department</th>
<th style="text-align: right;">turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alice</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bob</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">1.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amy</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ben</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">1.9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carol</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dan</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cindy</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doug</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eve</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">2.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frank</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ella</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">2.8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Floyd</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grace</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Henry</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">3.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gail</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hector</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">3.9</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="people-in-each-group" class="slide level2">
<h2>People in Each Group</h2>
<p>We can calculate the number of people in each group with the code below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href=""></a>dept_data <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href=""></a>  <span class="fu">group_by</span>(department) <span class="sc">|&gt;</span></span>
<span id="cb29-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">department</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">HR</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>You can see there are 4 people per group.</p>
</section>
<section id="department-data-factors" class="slide level2">
<h2>Department Data Factors</h2>
<p>We need to convert the department column to be a factor. And we need to set the reference group to “HR”.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href=""></a>dept_data <span class="ot">&lt;-</span> dept_data <span class="sc">|&gt;</span></span>
<span id="cb30-2"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">department =</span> <span class="fu">as_factor</span>(department)) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href=""></a>  <span class="fu">mutate</span>(<span class="at">department =</span> <span class="fu">fct_relevel</span>(department, <span class="st">"HR"</span>))</span>
<span id="cb30-4"><a href=""></a></span>
<span id="cb30-5"><a href=""></a><span class="fu">levels</span>(dept_data<span class="sc">$</span>department)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "HR"          "Sales"       "Engineering" "Marketing"  </code></pre>
</div>
</div>
<p>You can see from this output that Department has 4 levels, with HR as the reference group.</p>
<p>You know HR is the reference group because it’s listed first.</p>
</section>
<section id="the-contrast-matrix" class="slide level2">
<h2>The Contrast Matrix</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href=""></a><span class="fu">contrasts</span>(dept_data<span class="sc">$</span>department)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Sales Engineering Marketing
HR              0           0         0
Sales           1           0         0
Engineering     0           1         0
Marketing       0           0         1</code></pre>
</div>
</div>
<p>Remember we also use an intercept column to the left of these columns in the design matrix.</p>
<p>Each column in the above output asks: “Are you in this specific department?”</p>
<ul>
<li>c1: Are you in Sales? (0/1)</li>
<li>c2: Are you in Engineering? (0/1)</li>
<li>c3: Are you in Marketing? (0/1)</li>
</ul>
<p>HR people get all zeros—they’re identified by NOT being in any other department.</p>
<p><strong>Compare the contrast matrix</strong> above to the <strong>design matrix</strong> on the next slide. You can see that in the design matrix every person in a group receives a row from this contrast matrix.</p>
</section>
<section id="design-matrix-y-xb-4-groups" class="slide level2">
<h2>Design Matrix: y = Xb (4 Groups)</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/matrix-algebra-dept.png" class="quarto-figure quarto-figure-center" style="width:80.0%;height:100.0%"></p>
</figure>
</div>
</div>
</div>
<p>You can see in this Design Matrix that HR people do get 1 in intercept column - that a weight will be applied to. So it is the intercept weight that matters for HR people.</p>
<p>The contrast columns and the intercept column work together in the calculations.</p>
</section>
<section id="running-the-model" class="slide level2">
<h2>Running the Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href=""></a>lm_dept <span class="ot">&lt;-</span> <span class="fu">lm</span>(turnover <span class="sc">~</span> department, <span class="at">data =</span> dept_data)</span>
<span id="cb34-2"><a href=""></a><span class="fu">tidy</span>(lm_dept)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.0912871</td>
<td style="text-align: right;">21.908902</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">10.069757</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">7.745967</td>
<td style="text-align: right;">0.0000052</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentMarketing</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">15.491933</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Can you look at this output and determine the mean for each department?</p>
<p>Which departments have means that are significantly different from the HR mean?</p>
</section>
<section id="augment-the-data-2" class="slide level2">
<h2>Augment the Data</h2>
<p>Make predicted scores for each person/group</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href=""></a><span class="co"># Create augmented data with predictions and residuals</span></span>
<span id="cb35-2"><a href=""></a>dept_augmented <span class="ot">&lt;-</span> <span class="fu">augment</span>(lm_dept, <span class="at">data =</span> dept_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell augment">
<div class="cell-output-display">
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 7%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">name</th>
<th style="text-align: right;">employee_id</th>
<th style="text-align: left;">department</th>
<th style="text-align: right;">turnover</th>
<th style="text-align: right;">.fitted</th>
<th style="text-align: right;">.resid</th>
<th style="text-align: right;">.hat</th>
<th style="text-align: right;">.sigma</th>
<th style="text-align: right;">.cooksd</th>
<th style="text-align: right;">.std.resid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alice</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">0.6324555</td>
</tr>
<tr class="even">
<td style="text-align: left;">Bob</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">1.8</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">-1.2649111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amy</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.2</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">1.2649111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ben</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">HR</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">-0.6324555</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Carol</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">1.2649111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dan</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">-0.6324555</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cindy</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">0.6324555</td>
</tr>
<tr class="even">
<td style="text-align: left;">Doug</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">-1.2649111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eve</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">-0.6324555</td>
</tr>
<tr class="even">
<td style="text-align: left;">Frank</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.1</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">0.6324555</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ella</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">2.8</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">-1.2649111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Floyd</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.2</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">1.2649111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Grace</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.2</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">1.2649111</td>
</tr>
<tr class="even">
<td style="text-align: left;">Henry</td>
<td style="text-align: right;">14</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">3.8</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">-0.2</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1775251</td>
<td style="text-align: right;">0.1333333</td>
<td style="text-align: right;">-1.2649111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gail</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.1</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">0.6324555</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hector</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">3.9</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">-0.1</td>
<td style="text-align: right;">0.25</td>
<td style="text-align: right;">0.1874874</td>
<td style="text-align: right;">0.0333333</td>
<td style="text-align: right;">-0.6324555</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="visualizing-the-model-code-1" class="slide level2">
<h2>Visualizing the Model: Code</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href=""></a><span class="co"># Plot data points and predicted values</span></span>
<span id="cb36-2"><a href=""></a><span class="fu">ggplot</span>(dept_augmented, <span class="fu">aes</span>(<span class="at">x =</span> department,</span>
<span id="cb36-3"><a href=""></a>                            <span class="at">y =</span> turnover,</span>
<span id="cb36-4"><a href=""></a>                            <span class="at">group =</span> department)) <span class="sc">+</span></span>
<span id="cb36-5"><a href=""></a>  <span class="fu">geom_jitter</span>(<span class="at">width =</span> <span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href=""></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> .fitted, <span class="at">ymax =</span> .fitted),</span>
<span id="cb36-7"><a href=""></a>                <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linewidth =</span> <span class="dv">2</span>, <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb36-8"><a href=""></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Department"</span>, <span class="at">y =</span> <span class="st">"Turnover"</span>) <span class="sc">+</span></span>
<span id="cb36-9"><a href=""></a>  <span class="fu">theme_minimal</span>(<span class="at">base_size =</span> <span class="dv">18</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plot-department-model" class="slide level2">
<h2>Plot: Department Model</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/dept-augment-plot-1.png" class="quarto-figure quarto-figure-center" width="768"></p>
</figure>
</div>
</div>
</div>
<p>The lines show ŷ (predicted values) for each group—which equal the group means!</p>
<p>💬 <strong>Quick chat:</strong> Looking at this plot, which department has the highest turnover? Which has the lowest? (Just type the department names)</p>
</section>
<section id="interpreting-the-output-1" class="slide level2">
<h2>Interpreting the Output</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>2.0</td>
<td>Mean turnover for <strong>HR</strong> (reference)</td>
</tr>
<tr class="even">
<td>departmentSales</td>
<td>1.3</td>
<td>Sales mean is 1.3 higher than HR</td>
</tr>
<tr class="odd">
<td>departmentEngineering</td>
<td>1.0</td>
<td>Engineering mean is 1.0 higher than HR</td>
</tr>
<tr class="even">
<td>departmentMarketing</td>
<td>2.0</td>
<td>Marketing mean is 2.0 higher than HR</td>
</tr>
</tbody>
</table>
<p>Every coefficient is a comparison to the <strong>reference group</strong> (HR).</p>
</section>
<section id="verify-with-group-means-1" class="slide level2">
<h2>Verify with Group Means</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th>Estimate</th>
<th>Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>2.0</td>
<td>Mean turnover for <strong>HR</strong> (reference)</td>
</tr>
<tr class="even">
<td>departmentSales</td>
<td>1.3</td>
<td>Sales mean is 1.3 higher than HR</td>
</tr>
<tr class="odd">
<td>departmentEngineering</td>
<td>1.0</td>
<td>Engineering mean is 1.0 higher than HR</td>
</tr>
<tr class="even">
<td>departmentMarketing</td>
<td>2.0</td>
<td>Marketing mean is 2.0 higher than HR</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href=""></a>dept_data <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href=""></a>  <span class="fu">group_by</span>(department) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">mean_turnover =</span> <span class="fu">mean</span>(turnover))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">department</th>
<th style="text-align: right;">mean_turnover</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="calculation-example-alice-hr" class="slide level2 content-light">
<h2>Calculation Example: Alice (HR)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href=""></a><span class="fu">contrasts</span>(dept_data<span class="sc">$</span>department)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Sales Engineering Marketing
HR              0           0         0
Sales           1           0         0
Engineering     0           1         0
Marketing       0           0         1</code></pre>
</div>
</div>
<p>Alice’s row: Int = 1, c1 = 0, c2 = 0, c3 = 0</p>
<p>ŷ = 2.0(1) + 1.3(0) + 1.0(0) + 2.0(0)</p>
<p>ŷ = 2.0 + 0 + 0 + 0 = 2.0</p>
<p>All contrast switches are “off”—Alice only gets the intercept.</p>
</section>
<section id="calculation-example-carol-sales" class="slide level2 content-light">
<h2>Calculation Example: Carol (Sales)</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href=""></a><span class="fu">contrasts</span>(dept_data<span class="sc">$</span>department)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Sales Engineering Marketing
HR              0           0         0
Sales           1           0         0
Engineering     0           1         0
Marketing       0           0         1</code></pre>
</div>
</div>
<p>Carol’s row: Int = 1, c1 = 1, c2 = 0, c3 = 0</p>
<p>ŷ = 2.0(1) + 1.3(1) + 1.0(0) + 2.0(0)</p>
<p>ŷ = 2.0 + 1.3 + 0 + 0 = 3.3</p>
<p><strong>The “Light Switch” Logic:</strong> * Carol is in Sales <span class="math inline">\(\rightarrow\)</span> Sales switch is <strong>ON</strong> (1) * Carol is NOT in Eng/Mkt <span class="math inline">\(\rightarrow\)</span> Those switches are <strong>OFF</strong> (0)</p>
</section>
<section id="your-turn-calculate-ŷ-for-maria-marketing" class="slide level2 content-light">
<h2>Your Turn: Calculate ŷ for Maria (Marketing)</h2>
<p>Maria works in <strong>Marketing</strong>. Using the same model:</p>
<ul>
<li>b₀ = 2.0 (intercept)</li>
<li>b₁ = 1.3 (Sales)</li>
<li>b₂ = 1.0 (Engineering)</li>
<li>b₃ = 2.0 (Marketing)</li>
</ul>
<p><strong>Step 1:</strong> What are Maria’s row values? (Int = ?, c1 = ?, c2 = ?, c3 = ?)</p>
<p><strong>Step 2:</strong> Write the equation and plug in values</p>
<p><strong>Step 3:</strong> Calculate ŷ</p>
<p>Take 60 seconds. Put your answer in the chat when ready!</p>
</section>
<section id="your-turn-answer-1" class="slide level2 content-light">
<h2>Your Turn: Answer</h2>
<p>Maria is in <strong>Marketing</strong>.</p>
<table class="caption-top">
<colgroup>
<col style="width: 23%">
<col style="width: 46%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Step</th>
<th>What we do</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Find Maria’s row values</td>
<td>Int = 1, c1 = 0, c2 = 0, c3 = <strong>1</strong></td>
</tr>
<tr class="even">
<td>2</td>
<td>Write equation with values</td>
<td>ŷ = 2.0(1) + 1.3(0) + 1.0(0) + 2.0(<strong>1</strong>)</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Calculate</td>
<td>2.0 + 0 + 0 + 2.0 = <strong>4.0</strong></td>
</tr>
</tbody>
</table>
<p><strong>The “Light Switch” Logic:</strong></p>
<ul>
<li>Maria is in Marketing → Marketing switch is <strong>ON</strong> (1)</li>
<li>Maria is NOT in Sales/Eng → Those switches are <strong>OFF</strong> (0)</li>
</ul>
</section>
<section id="polling-question-3" class="slide level2 content-light">
<h2>Polling Question 3</h2>
<p>Quick check—this should be fast if you understood the a-1 rule.</p>
<blockquote>
<p>A categorical predictor has 6 levels. How many contrast columns will R create?</p>
</blockquote>
<ul>
<li><ol type="A">
<li>4</li>
</ol></li>
<li><ol start="2" type="A">
<li>5</li>
</ol></li>
<li><ol start="3" type="A">
<li>6</li>
</ol></li>
<li><ol start="4" type="A">
<li>7</li>
</ol></li>
</ul>
</section>
<section id="polling-question-3-answer" class="slide level2 content-light">
<h2>Polling Question 3: Answer</h2>
<p><strong>Correct answer: B) 5</strong></p>
<p>The <strong>a − 1 rule</strong>: With <em>a</em> groups, you need <em>a</em> − 1 contrast columns.</p>
<ul>
<li>6 groups → 6 − 1 = <strong>5 contrast columns</strong></li>
<li>The reference group is identified by having 0s on ALL contrast columns</li>
<li>You don’t need a column for the reference group because it’s captured by the intercept</li>
</ul>
</section>
<section id="additional-statistics-department-model" class="slide level2">
<h2>Additional Statistics: Department Model</h2>
<p><strong>R² from glance():</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href=""></a><span class="fu">glance</span>(lm_dept)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 2%">
<col style="width: 8%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 4%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">r.squared</th>
<th style="text-align: right;">adj.r.squared</th>
<th style="text-align: right;">sigma</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">logLik</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">deviance</th>
<th style="text-align: right;">df.residual</th>
<th style="text-align: right;">nobs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0.9538639</td>
<td style="text-align: right;">0.9423299</td>
<td style="text-align: right;">0.1825742</td>
<td style="text-align: right;">82.7</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6.808019</td>
<td style="text-align: right;">-3.616038</td>
<td style="text-align: right;">0.2469054</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">16</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="additional-statistics-department-model-1" class="slide level2">
<h2>Additional Statistics: Department Model</h2>
<p><strong>Descriptive Statistics by Department:</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href=""></a>dept_data <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href=""></a>  <span class="fu">group_by</span>(department) <span class="sc">|&gt;</span></span>
<span id="cb43-3"><a href=""></a>  <span class="fu">summarize</span>(<span class="at">mean_turnover =</span> <span class="fu">mean</span>(turnover),</span>
<span id="cb43-4"><a href=""></a>            <span class="at">sd_turnover =</span> <span class="fu">sd</span>(turnover),</span>
<span id="cb43-5"><a href=""></a>            <span class="at">n =</span> <span class="fu">n</span>())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">department</th>
<th style="text-align: right;">mean_turnover</th>
<th style="text-align: right;">sd_turnover</th>
<th style="text-align: right;">n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">HR</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1825742</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sales</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">0.1825742</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Engineering</td>
<td style="text-align: right;">3.0</td>
<td style="text-align: right;">0.1825742</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">4.0</td>
<td style="text-align: right;">0.1825742</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">1.02</td>
<td style="text-align: right;">1.58</td>
<td style="text-align: right;">10.07</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.72</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentMarketing</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">1.72</td>
<td style="text-align: right;">2.28</td>
<td style="text-align: right;">15.49</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="results-paragraph-department-turnover" class="slide level2 results-paragraph">
<h2>Results Paragraph: Department Turnover</h2>
<div style="font-size: 0.75em;">
<p>We examined whether department membership was associated with employee turnover (<em>N</em> = 16). We used linear regression with treatment coding, where HR served as the reference group.</p>
<p><strong>Descriptive statistics.</strong> HR employees (<em>n</em> = 4) had a mean turnover of 2.00 (<em>SD</em> = 0.18). Sales employees (<em>n</em> = 4) had <em>M</em> = 3.30 (<em>SD</em> = 0.18). Engineering employees (<em>n</em> = 4) had <em>M</em> = 3.00 (<em>SD</em> = 0.18). Marketing employees (<em>n</em> = 4) had <em>M</em> = 4.00 (<em>SD</em> = 0.18).</p>
<p><strong>Results.</strong> Each regression coefficient (<em>b</em>) represents the difference in turnover between a department and the reference group (HR). Sales employees had turnover 1.30 points higher than HR, <em>b</em> = 1.30, 95% CI [1.02, 1.58], <em>t</em>(12) = 10.07, <em>p</em> &lt; .001, <em>d</em> = 7.12, 95% CI [2.43, 11.81]. Engineering employees had turnover 1.00 points higher than HR, <em>b</em> = 1.00, 95% CI [0.72, 1.28], <em>t</em>(12) = 7.75, <em>p</em> &lt; .001, <em>d</em> = 5.48, 95% CI [1.71, 9.25]. Marketing employees had turnover 2.00 points higher than HR, <em>b</em> = 2.00, 95% CI [1.72, 2.28], <em>t</em>(12) = 15.49, <em>p</em> &lt; .001, <em>d</em> = 10.95, 95% CI [4.03, 17.88]. The overall model was significant, <em>F</em>(3, 12) = 82.70, <em>p</em> &lt; .001, explaining 95.4% of the variance in turnover, <em>R</em>² = .95, 95% CI [.84, .97].</p>
</div>
</section>
<section id="where-do-the-p-values-come-from" class="slide level2 smaller">
<h2>Where Do the p-Values Come From?</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.0912871</td>
<td style="text-align: right;">21.908902</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">10.069757</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">7.745967</td>
<td style="text-align: right;">0.0000052</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentMarketing</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">15.491933</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>The statistic column is a t-value from a t-test</strong></p>
<p>Each row tests whether that coefficient is significantly different from zero:</p>
<p><span class="math display">\[t = \frac{\text{estimate}}{\text{std.error}}\]</span></p>
<p>For example, the Sales coefficient: <span class="math inline">\(t = \frac{1.30}{0.13} = 10.07\)</span></p>
<p><strong>The p.value is simply the p-value from that t-test</strong>, testing the null hypothesis that the true coefficient equals zero. Using <em>t</em> = 10.07 from <code>tidy()</code> and <em>df</em> = 12 from <code>glance()</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href=""></a><span class="dv">2</span> <span class="sc">*</span> <span class="fu">pt</span>(<span class="at">q =</span> <span class="fl">10.07</span>, <span class="at">df =</span> <span class="dv">12</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0000003322015</code></pre>
</div>
</div>
<p>This matches the p.value in the table (we multiply by 2 for a two-tailed test).</p>
<p>Remember df from 6060? When cell sizes are equal <span class="math inline">\(df = a(n-1) = 4(4-1)=4(3)=12\)</span>.</p>
</section>
<section id="understanding-standard-errors-in-treatment-coding" class="slide level2 smaller">
<h2>Understanding Standard Errors in Treatment Coding</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.0912871</td>
<td style="text-align: right;">21.908902</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">10.069757</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">7.745967</td>
<td style="text-align: right;">0.0000052</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentMarketing</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">15.491933</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Why do the standard errors differ?</strong></p>
<ul>
<li><strong>Intercept SE:</strong> This is the standard error of the reference group’s mean <em>alone</em></li>
</ul>
<p><span class="math display">\[SE_{\text{intercept}} = \sqrt{\frac{MSE}{n_{\text{reference}}}} = \sqrt{\frac{MSE}{4}}\]</span></p>
<ul>
<li><strong>Coefficient SEs:</strong> Each coefficient is a <em>difference</em> between two means, so uncertainty from both groups combines</li>
</ul>
<p><span class="math display">\[SE_{\text{coefficient}} = \sqrt{MSE \times \left(\frac{1}{n_{\text{reference}}} + \frac{1}{n_{\text{group}}}\right)} = \sqrt{MSE \times \left(\frac{1}{4} + \frac{1}{4}\right)}\]</span></p>
<p>The coefficient SEs are larger because estimating a difference involves uncertainty from <em>two</em> groups. If you want to check these numbers you can calculate them. Note you need <strong>sigma</strong> from the glance() output. Simply square it so <span class="math inline">\(MSE = sigma^2\)</span></p>
</section>
<section id="why-are-the-three-coefficient-ses-identical" class="slide level2">
<h2>Why Are the Three Coefficient SEs Identical?</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.0912871</td>
<td style="text-align: right;">21.908902</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentSales</td>
<td style="text-align: right;">1.3</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">10.069757</td>
<td style="text-align: right;">0.0000003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">departmentEngineering</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">7.745967</td>
<td style="text-align: right;">0.0000052</td>
</tr>
<tr class="even">
<td style="text-align: left;">departmentMarketing</td>
<td style="text-align: right;">2.0</td>
<td style="text-align: right;">0.1290994</td>
<td style="text-align: right;">15.491933</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>In this <strong>balanced design</strong> (n = 4 per group), each coefficient compares a group of 4 to the reference group of 4. The formula is identical for all three:</p>
<p><span class="math display">\[\sqrt{MSE \times \left(\frac{1}{4} + \frac{1}{4}\right)} = \sqrt{MSE \times 0.5}\]</span></p>
<p><strong>How does reference group choice affect SEs?</strong></p>
<ul>
<li><strong>Balanced design (equal n):</strong> Changing the reference group doesn’t change the SEs</li>
<li><strong>Unbalanced design:</strong> Choosing a <em>larger</em> reference group decreases all SEs (both intercept and coefficients), maximizing precision for all comparisons</li>
</ul>
</section>
<section id="the-big-picture-what-weve-learned" class="slide level2">
<h2>The Big Picture: What We’ve Learned</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="reg-cat-part1_files/figure-revealjs/big-picture-visual-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Key takeaways before the break:</strong></p>
<ol type="1">
<li>ŷ = estimated mean for people with those predictor values</li>
<li>Treatment coding uses 0/1 “switches” to turn coefficients on/off</li>
<li>Intercept = reference group mean; coefficients = differences from reference</li>
</ol>
</section>
<section id="references" class="slide level2">
<h2>References</h2>
<p>American Psychological Association. (2020). <em>Publication manual of the American Psychological Association</em> (7th ed.). https://doi.org/10.1037/0000165-000</p>
<p>Butler, A. C., Chapman, J. E., Forman, E. M., &amp; Beck, A. T. (2006). The empirical status of cognitive-behavioral therapy: A review of meta-analyses. <em>Clinical Psychology Review, 26</em>(1), 17–31. https://doi.org/10.1016/j.cpr.2005.07.003</p>
<p>Cohen, J. (1988). <em>Statistical power analysis for the behavioral sciences</em> (2nd ed.). Lawrence Erlbaum Associates.</p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="reg-cat-part1_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="reg-cat-part1_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="reg-cat-part1_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="reg-cat-part1_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
multiplex: {
  secret: null,
  id: '350487c243bd086167828e2f3e09a7baa9fe1073c803d07501db9dcd3c7e3bab',
  url: 'https://multiplex.up.railway.app/'
},
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'fade',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1024,

        height: 768,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>